### ISSUE TITLE
Deployment information

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#11]
Hi again, Im thinking that expanded documentation on how to deploy the server would be needed.
It is explained how to do it in local but not really on GH pages. You only provide a link to your own yml file.
The issue is that by using de default script provided by hugo [here](https://gohugo.io/hosting-and-deployment/hosting-on-github/) the site fails to deploy in this new update and before it was working.

**Comment by kaiiiz** [comment]
What problem do you encounter while using the default script? I suspect that you need to comment out `extended: true` since Monochrome uses SCSS.

```
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true
```

BTW, PRs are always welcome to improve the document.
