### ISSUE TITLE
Is it possible to display and/or filter by tags?

### ISSUE THREAD

**Issue by ToddMCr** [kaiiiz/hugo-theme-monochrome#53]
I have a content directory that looks like:
```
content
    ├———— _index.md
    ├———— about
    |       └———— index.md
    └———— posts
            ├———— _index.md
            ├———— my-first-post.md
            └———— my-second-post.md

```

and a `config/_default/menus.toml` file that has:
```toml
[[navbar]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

[[navbar]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
```

---
I'm wondering if it's possible to
1) display the tags of a given blogpost, for example `content/posts/my-first-post.md`:
```md
+++
title = 'My First Post'
date = 2024-06-08
tags = ["stats"]
+++

content
```

this blogpost has the tag `"stats"`, but it does not display in `Posts` or if I click on the actual post:

<img width="811" alt="image" src="https://github.com/kaiiiz/hugo-theme-monochrome/assets/168316945/269b6c1e-ed20-48e9-a3f7-226ec4448304">
<img width="819" alt="image" src="https://github.com/kaiiiz/hugo-theme-monochrome/assets/168316945/a6b128ec-f5db-4335-bec7-30e8024cd507">

2) My other question is it is possible to set up something in `Posts` so a user could filter for a particular tag(for example, if someone wanted to read only blogposts pertaining to stats, they would filter by the `"stats"` tag)

Thank you!
