### ISSUE TITLE
`enable_header_anchor = true` only works for _index.md

### ISSUE THREAD

**Issue by Silejonu** [kaiiiz/hugo-theme-monochrome#55]
Only `_index.md` is affected by `enable_header_anchor = true`. Other pages don't have any anchor.

On Arch Linux, up-to-date:  
hugo v0.127.0+extended linux/amd64 BuildDate=unknown

```bash
$ git submodule status
 ee549d5018a8fe105031ff7b9263824a3f0be54c themes/hugo-theme-monochrome (v3.1.0-2-gee549d5)

```

My `hugo.toml`:

```toml
baseURL = 'https://myweb.site'
languageCode = 'fr-fr'
defaultContentLanguage = "fr-fr"
title = 'My website'
theme = 'hugo-theme-monochrome'

[params]
footer = 'my footer'
enable_toc = true
enable_collapsible_toc = true
enable_site_search = true
enable_header_anchor = true
author = 'Silejonu'
enable_open_graph = false
enable_twitter_cards = false
color_scheme = 'dark'

[markup.highlight]
codeFences = false
lineNos = false
[param]
  [params.syntax_highlight]
  lib = "prism.js"
    [params.syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = true

[outputs]
home = ["HTML", "RSS", "JSON"]
```

My `content/_index.md`:

```md
+++
title = 'Accueil'
date = 2024-06-12T11:32:24Z
type = 'list'
+++

# Header 1

# Header 1.2

## Header 2
```

My `content/test.md`:

```md
+++
title = 'Test'
date = 2024-06-12T21:28:08Z
draft = true
header_anchor = true
+++

# Header 1

# Header 1.2

## Header 2
```

**Comment by kaiiiz** [comment]
I've tested this on the latest release (v3.1.0) but can not reproduce. Can you provide a reproducible repo? Thanks!

**Comment by Creatur3245** [comment]
Issue #55:

Below is an example of a minimal reproducible setup that mimics your configuration and content so you (or someone else) can test and debug the issue. You can use this as a starting point for reporting the bug or testing potential fixes.

---

### Repository Structure

Create a directory with the following structure:

```
hugo-repro/
├── config.toml
├── content/
│   ├── _index.md
│   └── test.md
└── themes/
    └── hugo-theme-monochrome/   (git submodule or local clone)
```

---

### Step 1. Create `config.toml`

Create a file named `config.toml` in the root of your repository with the following content:

```toml
baseURL = "https://myweb.site"
languageCode = "fr-fr"
defaultContentLanguage = "fr-fr"
title = "My website"
theme = "hugo-theme-monochrome"

[params]
footer = "my footer"
enable_toc = true
enable_collapsible_toc = true
enable_site_search = true
enable_header_anchor = true
author = "Silejonu"
enable_open_graph = false
enable_twitter_cards = false
color_scheme = "dark"

[markup.highlight]
codeFences = false
lineNos = false

[param]
  [params.syntax_highlight]
  lib = "prism.js"
    [params.syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = true

[outputs]
home = ["HTML", "RSS", "JSON"]
```

---

### Step 2. Create Content Files

#### `content/_index.md`

Create a file named `_index.md` under the `content` directory with:

```markdown
+++
title = "Accueil"
date = 2024-06-12T11:32:24Z
type = "list"
+++

# Header 1

# Header 1.2

## Header 2
```

#### `content/test.md`

Create another file named `test.md` under the `content` directory with:

```markdown
+++
title = "Test"
date = 2024-06-12T21:28:08Z
draft = true
header_anchor = true
+++

# Header 1

# Header 1.2

## Header 2
```

---

### Step 3. Add the Theme

If you’re using the theme as a git submodule, run in the repository root:

```bash
git submodule add https://github.com/<username>/hugo-theme-monochrome.git themes/hugo-theme-monochrome
git submodule update --init --recursive
```

*(Replace the URL with the proper repository if needed.)*

Alternatively, you can download or clone the theme into the `themes/hugo-theme-monochrome` directory.

---

### Step 4. Build & Serve the Site

Make sure you have Hugo installed (v0.127.0+extended, as mentioned). Then, from the repository root run:

```bash
hugo server
```

Now inspect the pages:

- *Homepage (`/`)*: Should display header anchors (enabled via `enable_header_anchor = true` in the global params).

- *Test page (`/test/`)*: Even though `header_anchor = true` is set in the front matter, you should observe that the header anchors are not applied.

---

### Observations & Next Steps

- *Reproducibility*: This minimal repo should reproduce the issue where `enable_header_anchor` only appears to work on `_index.md` pages (or list-type pages) and not on regular content pages.
  
- *Debugging*:

  - Verify if the theme’s partials or shortcodes responsible for rendering header anchors are conditioned on page type.

  - Check if the theme’s documentation or repository issue tracker contains any notes regarding this behavior.

  - Experiment by modifying the theme’s templates to see if the header anchor logic can be applied to regular pages.

- *Reporting the Issue*: If you decide to report this as a bug, include the above repository structure, your Hugo version, and a detailed description of the behavior. A link to a GitHub repository (or a ZIP archive) containing the above minimal reproduction is ideal.

---

### Conclusion

This setup should help isolate the problem. You can now either dive into the theme’s code to modify its behavior or file a detailed issue on the theme’s repository with your findings and the minimal reproducible example.

Let me know if you need further assistance/ more details/ or how it went!
