### ISSUE TITLE
How do I change the global font style?

### ISSUE THREAD

**Issue by Gu-f** [kaiiiz/hugo-theme-monochrome#64]
I want to set a font of my own and have it globally valid. What should I do?

**Comment by kaiiiz** [comment]
Regarding the accessibility issue raised in [https://github.com/kaiiiz/hugo-theme-monochrome/issues/66](https://github.com/kaiiiz/hugo-theme-monochrome/issues/66), I believe the theme should respect the user’s browser settings. If a fixed font size is necessary, you can adjust the `font-size` value in `color.scss`.

Example:

```scss
html {
  color: var(--color-text);
  background: var(--color-background);
  font-size: 16px; // adjust this value as needed
}
```
